### ISSUE TITLE
initialization issue

### ISSUE THREAD

**Issue by unilo147** [Deltares/dfm_tools#423]
Hi!
I installed this package today and I encountered such issue during importing packages in Python: "ValueError: mutable default <class 'numpy.ndarray'> for field face_nodes is not allowed: use default_factory".

To bypass this I changed to comment this part:
    # if f._field_type is _FIELD and f.default.__class__.__hash__ is None:
    #     raise ValueError(f'mutable default {type(f.default)} for field '
    #                      f'{f.name} is not allowed: use default_factory')

If you know how to correct this, I would be glad.
Cheers.

**Comment by veenstrajelmer** [comment]
@unilo147 are you using py3.11 by any chance? Please see this issue: https://github.com/Deltares/MeshKernelPy/issues/54
This issue is solved the solution was not released yet. It will probably happen this or next week, but in the meantime you could create a python 3.9/3.10 environment. Please let me know if that works for you.

**Comment by unilo147** [comment]
Thank you for your response and yes, I'm using py3.11 :)

**Comment by veenstrajelmer** [comment]
Assuming my suggestion will solve your problem. If you want to keep using python 3.11, please keep an eye out for meshkernel 2.1.0 at https://github.com/Deltares/MeshKernelPy/releases and reinstall dfm_tools after that.

**Comment by veenstrajelmer** [comment]
@unilo147, meshkernel 2.1.0 was released yesterday and is now available via pip. Therefore, your installation should now also work with python 3.11
