### ISSUE TITLE
what dfm_tools had get_ncmodeldata ? 

### ISSUE THREAD

**Issue by nyanyaleam** [Deltares/dfm_tools#701]

**Comment by veenstrajelmer** [comment]
It was not tagged and released back then, so there is no real version that is released. Therefore, it is recommended to update your code. If you really want it, you can go to a version on github, somewhere before the first release (0.11.0), since I see in the changelog that is where the function was deprecated. You can then pip install that version with a git-link. There is not support for this.

**Comment by veenstrajelmer** [comment]
Please also have a look in https://github.com/Deltares/dfm_tools/issues/716, where a user asks support with rewriting their code. I will close this issue now, but feel free to comment here again.
