### ISSUE TITLE
help rewriting a line containing a deprecated function

### ISSUE THREAD

**Issue by aemondd** [Deltares/dfm_tools#716]
hey, 
currently stuck with `get_ncmodeldata` function which is deprecated, saw postprocessing notebook and couldn't debug the code, need help rewriting this line without the get_ncmodeldata : 
`waterdepth = get_ncmodeldata(file_nc=output_map, varname='Mesh2d_waterdepth', timestep='all', silent=True)[:,order]`
thank you very much

**Comment by veenstrajelmer** [comment]
It depends a bit on what you are trying to do with the `order` variable. You are using it as an indexer for the second dimension of the resulting array, which is the face dimension. So in principle, this should work:

```python
import dfm_tools as dfmt
# open the mapfile as a xugrid UgridDataset (similar to xarray Dataset)
uds = dfmt.open_partitioned_dataset(file_nc=file_nc)
# print the Mesh2d_waterdepth DataArray so you can see the dimension names, I assume `face_dimension` for now, but it is likely something like `nmesh2d_face`
print(uds.Mesh2d_waterdepth)
# use the `order` variable to index on the face dimension
waterdepth_da = uds.Mesh2d_waterdepth.isel(face_dimension=order)
# convert to a numpy array, which is what get_ncmodeldata returned
waterdepth = waterdepth_da.to_numpy()
```

If this is all you want to do, this will work. However, you might get stuck on a next line of code since all is slightly different than it was. It depends a bit what the `order` variable is used for, or what your usecase is. For instance:
- it might be that you want to crop the dataset and in that case the method used in block [10] of the [postprocessing notebook](https://github.com/Deltares/dfm_tools/blob/main/docs/notebooks/postprocessing_example.ipynb) might be more convenient
- if you are using `order` to change the order of the dataset to align it with another mapfile for instance, please have a look at [reindex_like](https://deltares.github.io/xugrid/api/xugrid.UgridDatasetAccessor.reindex_like.html)
- in general, we now make use of xarray and xugrid which brings a bunch of new features. In case you are new to xarray, I can recommend [their 45 minute guide](https://tutorial.xarray.dev/overview/xarray-in-45-min.html). The [xugrid user guide](https://deltares.github.io/xugrid/user_guide.html) is a good place to contine after that.

If this does not work for you, please provide additional context with what you want to achieve.

**Comment by veenstrajelmer** [comment]
closed due to inactivity, please feel free to comment to this issue anyway.
