### ISSUE TITLE
Add option for rotated rectangle for grid generation

### ISSUE THREAD

**Issue by simonweppe** [Deltares/dfm_tools#800]
A big thank you for your work..it's really fast-tracking the use of DelftFM.

Just a suggestion to better fit with the coastlines orientation for examples.

**Comment by veenstrajelmer** [comment]
Hi @simonweppe, thank you for your suggestion. This has been considered, but it is a bit tricky to do this properly (orthogonal) in all use cases automatically. Also, in dfm_tools we use extents (lat/lon min/max) and if you want to include an angle you have to use the meshkernel function with lat/lon min and dx/dy, so compute the latter yourself. This would be a bit of trial and error since the dx/dy for spherical grids are recalculated to get orthogonal grids. Since it is a bit to complex and situation dependent, it is not included in the basic dfm_tools function.

However, there is a meshkernel issue about orthogonality here: https://github.com/Deltares/MeshKernelPy/issues/113. This also includes example meshkernel code of how to generate such a base grid, which you can just insert in the modelbuilder code. You can use the refinement/cutting functions of dfm_tools since it also works with these meshkernel instances.

**Comment by simonweppe** [comment]
Thanks for quick reply @veenstrajelmer. 

Ok makes sense...in my case I will always be fine with using a cartesian grid (I think!) so that example you linked is really useful to get going. 

From what I understand `dfm_tools` assumes a lon/lat grid in all methods so after I get my cartesian grid (e.g rotated one), an option could be to create a dummy version of my cartesian grid in lon/lat to be able to then be able to use all the boundary/initial conditions generation tools. Then run in cartesian mode so that there are no orthogonlity issues. Does that sound right ?

Thanks again, and will be happy to contribute what I can.

**Comment by veenstrajelmer** [comment]
If you would create a cartesian grid you would need a projected coordinate system, so no lat/lon but something in meters like UTM. This is currently not yet supported by the modelbuilder. If you would create a cartesian grid with lat/lon coordinates (degrees), the model computation will interpret the degrees as meters and the model result will be very wrong.

If you want to generate a rotated spherical grid, you can just try it directly with the meshkernel calls. Would that work for you?

**Comment by simonweppe** [comment]
Yes I think it will be fine - thanks !
