### ISSUE TITLE
Capital sentive variable names in .bc files

### ISSUE THREAD

**Issue by RHoeg** [Deltares/dfm_tools#874]
Hi,

The parameter names and the 'Forcing' header in the .bc files are case sensitive in Delft3D FM Suite 2023.02. Therefore, the created .bc files are not imported if this is not adjusted (see example below). It would be good to either adjust this in the tool or remove the case sensitivity in the FM Suite software.

From the model builder tool:
[Forcing]
name     = Gambia_bnd_0001
function = astronomic
factor   = 1.0

Accepted by FM suite:
[forcing]
Name     = Gambia_bnd_0001
Function = astronomic
Factor   = 1.0

The modelbuilder works well for the creation of the files.

Kind regards,
Roel

**Comment by veenstrajelmer** [comment]
Indeed @RHoeg, this is not aligned at the moment. This was reported before in https://github.com/Deltares/dfm_tools/issues/710, which also contains a sort of workaround that might not work in all cases. The issue will be resolved in the Delft3D FM Suite user interface. It might even already be resolved in the latest release, otherwise I hope it will be resolved in the next one. Since it requires no code change in dfm_tools, I will close this issue here.
